### PR TITLE
Added template

### PR DESCRIPTION
**Pull request by JuanM04**
See https://github.com/railwayapp/starters/pull/196

### CODE REVIEW

**Comment by JuanM04** [comment]
How can I configure the Deploy button? I see all the other examples have an URL like this: `https://railway.app/new/template/vaultwarden` - I'd wish to know where set, for ezample, "You need a Postgres database", "You need an ADMIN_TOKEN env var", etc

**Comment by FarazPatankar** [comment]
Hey @JuanM04, have you already created the template? If you visit the [button page](https://railway.app/button), you should see the new UI which allows you to create the new style of templates.

I can manually update the template code for you once you set it up.

**Comment by JuanM04** [comment]
@FarazPatankar https://railway.app/new/template/4PTYse

The only thing left is to change the github repo of the template

**Comment by FarazPatankar** [comment]
Could you elaborate? I looked at the linked repo and it only has a README.

Can we make all the required changes and then I'll update the code + add it to the starters page?

**Comment by JuanM04** [comment]
> Could you elaborate? I looked at the linked repo and it only has a README.

It's actually pointing to https://github.com/JuanM04/vaultwarden/tree/init. I don't know why the link points to the `main` branch.

**Review by FarazPatankar — APPROVED** [review]

**Pull request merged**
